{{- with .Values.route }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  labels:
    {{- include "quarkus-template.labels" $ | nindent 4 }}
  name: {{ include "quarkus-template.name" $ }}
  namespace: {{ include "quarkus-template.namespace" $ }}
spec:
  {{- if .host }}
  host: {{ .host }}
  {{- end }}
  {{- if .path }}
  path: {{ .path }}
  {{- end }}
  port:
    targetPort: {{ $.Values.route.targetPort }}
  to:
    kind: Service
    name: {{ include "quarkus-template.name" $ }}
  tls:
    termination: edge
  wildcardPolicy: None
{{- end }}
