apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-template.name" $ }}
  namespace: "{{ .Values.app.namespace }}"
  labels:
    {{- include "quarkus-template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quarkus-template.selectorLabels" . | nindent 4 }}
